spring:
  datasource:
    url: jdbc:mysql://${PROD_MYSQL_SERVER}:${LOCAL_MYSQL_PORT}/capstone?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${PROD_MYSQL_USERNAME}
    password: ${PROD_MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect