spring:
  datasource:
    url: jdbc:mysql://localhost:${LOCAL_MYSQL_PORT}/smartPets?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true