spring:
  datasource:
    url: jdbc:mysql://${PROD_MYSQL_SERVER}:${LOCAL_MYSQL_PORT}/capstone?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${PROD_MYSQL_USERNAME}
    password: ${PROD_MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  servlet:
    session:
      timeout: 999d

kakao:
  rest-api-key: ${PROD_KAKAO_REST_API_KEY}
  redirect-uri: ${PROD_KAKAO_REDIRECT_URI}
  admin-key: ${PROD_KAKAO_ADMIN_KEY}

naver:
  client-id: ${PROD_NAVER_CLIENT_ID}
  client-secret: ${PROD_NAVER_CLIENT_SECRET}
  redirect-uri: ${PROD_NAVER_REDIRECT_URI}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    stack.auto: false
    region.static: ${AWS_REGION}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
