spring:
  datasource:
    url: jdbc:mysql://localhost:${LOCAL_MYSQL_PORT}/smartPets?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kakao:
  rest-api-key: ${LOCAL_KAKAO_REST_API_KEY}
  redirect-uri: ${LOCAL_KAKAO_REDIRECT_URI}
  admin-key: ${LOCAL_KAKAO_ADMIN_KEY}

naver:
  client-id: ${LOCAL_NAVER_CLIENT_ID}
  client-secret: ${LOCAL_NAVER_CLIENT_SECRET}
  redirect-uri: ${LOCAL_NAVER_REDIRECT_URI}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    stack.auto: false
    region.static: ${AWS_REGION}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}